### PR TITLE
RIR

### PR DESCRIPTION
**Pull request by JanEickholt**
rewritten in rust

### CODE REVIEW

**Comment by OusmBlueNinja** [comment]
what the fuck

**Comment by OusmBlueNinja** [comment]
i give up

**Comment by JanEickholt** [comment]
better email generation and idea for weights by @BRICKRAID
email list (shorter version) by @B1GBOOM420
idea for rate limiting by @HarryJamesGreen

**Comment by OusmBlueNinja** [comment]
i don't think this will get merged, just due to the fact that this project is supposed to be simple to understand and that its for learning.

**Comment by Hexdigest123** [comment]
> i don't think this will get merged, just due to the fact that this project is supposed to be simple to understand and that its for learning.

Blasphemy

**Comment by BRICKRAID** [comment]
Shouldn’t it be merged for learning then? There’s a few good bits that
beginners would find interesting in here. The majority of this is just if
statements so it’s pretty simple, do you have any examples of what parts
make it not simple to understand?

Best Regards,
*Ryan Schulte*

**Comment by 0ddFl3xx** [comment]
> rewritten in rust

You are CRACKED bro! Are you going to publish this to npm or just for this repo?

**Comment by JanEickholt** [comment]
> You are CRACKED bro! Are you going to publish this to npm or just for this repo?

tbh i never got to convert a rust package to npm, also don't quite know which part you would want to use as a library, feel free to do so

**Comment by JanEickholt** [comment]
This pr is being closed, since the project is being continued in python for learning purposes and doesn't seek efficiency / isn't supposed to be used against "real" targets.
Had fun rewriting it, even if it didn't quite make it into the project.

**Pull request closed without merging**
